[package]
name = "pcie"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
bit_field = "0.10"
bitflags = "2"
pci_types = "0.10"

[dev-dependencies]
bare-test = "0.1"

[build-dependencies]
sparreal-macros = "0.0.5"
